### PR TITLE
Added aliases for kubectl.

### PR DESCRIPTION
**Pull request by JohnPhoto**
Changes proposed in this PR:
- Added (a few) aliases for `kubectl` (Kubernetes control). Origin: https://github.com/ahmetb/kubectl-aliases

If this just adds bloat, feel free to decline.

### CODE REVIEW

**Comment by JohnPhoto** [comment]
If you are not using kubectl this will most problably make your console feel unnecessary slugish at start.

**Comment by bstream** [comment]
Would you consider it a good enough option to put this stuff in `.config/fish/overrides.fish`? I do realize that there is currently no overrides for bash but that can be added.

My doubts are the two you mentioned:
* bloat (I know I have more bloat in there that I probably should remove... :) )
* *sluggishness*

**Comment by JohnPhoto** [comment]
I am not familiar with the overrides, but if it works I’m good with it.

I do not mind removal in bash since I primarily use fish.

Will update PR, when at my laptop.

**Comment by bstream** [comment]
https://github.com/bstream/dots/pull/14 😎

**Comment by JohnPhoto** [comment]
Doh... 🤣

**Pull request closed without merging**
